### ISSUE TITLE
Argo CD cluster is not adding properly

### ISSUE THREAD

**Issue by holoGDM** [oboukili/terraform-provider-argocd#101]
Im adding cluster in such way:

```
data "google_container_cluster" "cluster" {
  project  = "my-infrastructure"
  name     = "gke-cluster"
  location = "europe-west4"
}


output "gke_endpoint" {
  value = data.google_container_cluster.cluster.endpoint
}

output "gke_ca_certificate" {
  value = data.google_container_cluster.cluster.master_auth.0.cluster_ca_certificate
}

output "gke_client_certificate" {
  value     = data.google_container_cluster.cluster.master_auth.0.client_certificate
}

output "gke_client_key" {
  value = data.google_container_cluster.cluster.master_auth.0.client_key
}

resource "argocd_cluster" "gke" {
  server = format("https://%s", data.google_container_cluster.cluster.endpoint)
  name   = "gke-infra-test"

  config {
    tls_client_config {
      ca_data   = base64decode(data.google_container_cluster.cluster.master_auth.0.cluster_ca_certificate)
      cert_data = base64decode(data.google_container_cluster.cluster.master_auth.0.client_certificate)
      key_data  = base64decode(data.google_container_cluster.cluster.master_auth.0.client_key)
    }
  }
}
```

And it is successfully added but it doesnt want to work and im getting such error:
```
failed to sync cluster https://123.123.123.123: failed to load initial state of resource Role.rbac.authorization.k8s.io: roles.rbac.authorization.k8s.io is forbidden: User "client" cannot list resource "roles" in API group "rbac.authorization.k8s.io" at the cluster scope
```

am i missing something?

EDIT:

Every check there is diffrent resource problem:

```
failed to sync cluster https://123.123.123.123: failed to load initial state of resource CertificateSigningRequest.certificates.k8s.io: certificatesigningrequests.certificates.k8s.io is forbidden: User "client" cannot list resource "certificatesigningrequests" in API group "certificates.k8s.io" at the cluster scope
```

EDIT2:

With bearer_token it is working as expected, but example for GKE (like above not). Working conf for GKE:

```
resource "argocd_cluster" "gke" {
  server = format("https://%s", data.google_container_cluster.cluster.endpoint)
  name   = var.cluster.name

  config {
    tls_client_config {

      bearer_token = data.google_client_config.default.access_token
      ca_data   = base64decode(data.google_container_cluster.cluster.master_auth.0.cluster_ca_certificate)
    }
  }
}
```

**Comment by oboukili** [comment]
I think it has been fixed with the v2.0.0 release, cluster 'upsert' has been set to `true` upon cluster addition (to benefit from this you will have to either taint/recreate your `argocd_cluster` ressource, or add the cluster through the `argocd` cli, then import it in the workspace).

**Comment by robert-ingeniousio** [comment]
It is still not working my test configuration:

```
data "google_client_config" "default" {
}

data "google_container_cluster" "cluster" {
  project  = var.cluster.project
  name     = var.cluster.name
  location = var.cluster.location
}

output "gke_endpoint" {
  value = data.google_container_cluster.cluster.endpoint
}

output "gke_ca_certificate" {
  value = data.google_container_cluster.cluster.master_auth.0.cluster_ca_certificate
}

output "gke_client_certificate" {
  value = data.google_container_cluster.cluster.master_auth.0.client_certificate
}

output "client_key" {
  value = data.google_container_cluster.cluster.master_auth.0.client_key
}

resource "argocd_cluster" "gke" {
  server = format("https://%s", data.google_container_cluster.cluster.endpoint)
  name   = var.cluster.name

  config {
    tls_client_config {
      ca_data   = "${base64decode(data.google_container_cluster.cluster.master_auth.0.cluster_ca_certificate)}"
      cert_data = "${base64decode(data.google_container_cluster.cluster.master_auth.0.client_certificate)}"
      key_data  = "${base64decode(data.google_container_cluster.cluster.master_auth.0.client_key)}"
    }
  }
}
```
im getting same errors like above
